# sh certora/scripts/verifyPoolCol.sh afterDepositAmountGzero
# sh certora/scripts/verifyPoolCol.sh tradeAllBntTokensShouldFail
# sh certora/scripts/verifyPoolCol.sh tradeWhenZeroTokensRevert
# sh certora/scripts/verifyPoolCol.sh tradeWhenZeroLiquidity
# sh certora/scripts/verifyPoolCol.sh rateIsPositive
sh certora/scripts/verifyPoolCol.sh averageRateNonZero
# sh certora/scripts/verifyPoolCol.sh differentTokens
# sh certora/scripts/verifyPoolCol.sh notHasPoolNotHasPoolToken
# sh certora/scripts/verifyPoolCol.sh zeroPoolTokensZeroStakedBalance
# sh certora/scripts/verifyPoolCol.sh consistentTradingLiquidity
# sh certora/scripts/verifyPoolCol.sh networkFeePPM
# sh certora/scripts/verifyPoolCol.sh withdrawWhenBntIsZero


# sh certora/scripts/verifyBancorNetwork.sh invariantValidPoolAfterTrade
# sh certora/scripts/verifyBancorNetwork.sh invariantValidPoolAfterDeposit
# sh certora/scripts/verifyBancorNetwork.sh underlyingToPTinverse
# sh certora/scripts/verifyBancorNetwork.sh underlyingToPTmono
# sh certora/scripts/verifyBancorNetwork.sh checkInitWithdraw
# sh certora/scripts/verifyBancorNetwork.sh noDoubleCancelling
# sh certora/scripts/verifyBancorNetwork.sh tradeA2BLiquidity
# sh certora/scripts/verifyBancorNetwork.sh tradeBntLiquidity
# sh certora/scripts/verifyBancorNetwork.sh untradeablePT
# sh certora/scripts/verifyBancorNetwork.sh afterTradingPTBalanceIntact
# sh certora/scripts/verifyBancorNetwork.sh cancellingAlwaysPossible
# sh certora/scripts/verifyBancorNetwork.sh RequestRegisteredForValidProvider
# sh certora/scripts/verifyBancorNetwork.sh noDoubleWithdrawalBNT
# sh certora/scripts/verifyBancorNetwork.sh doubleWithdrawHelper
# sh certora/scripts/verifyBancorNetwork.sh depositBntIntegrity
# sh certora/scripts/verifyBancorNetwork.sh depositTknIntegrity
# sh certora/scripts/verifyBancorNetwork.sh afterTradeSumOfTokenBalanceIntact
# sh certora/scripts/verifyBancorNetwork.sh depositBNTtransferPTsToProvider

# sh certora/scripts/verifyBancorNetwork.sh noPoolNoParty1
# sh certora/scripts/verifyBancorNetwork.sh noPoolNoParty2
# sh certora/scripts/verifyBancorNetwork.sh noPoolNoParty3
# sh certora/scripts/verifyBancorNetwork.sh noPoolNoParty4
# sh certora/scripts/verifyBancorNetwork.sh noPoolNoParty5
# sh certora/scripts/verifyBancorNetwork.sh noPoolNoParty6
# sh certora/scripts/verifyBancorNetwork.sh reentrancyCheck1
# sh certora/scripts/verifyBancorNetwork.sh reentrancyCheck2
# sh certora/scripts/verifyBancorNetwork.sh reentrancyCheck3
# sh certora/scripts/verifyBancorNetwork.sh reentrancyCheck4
# sh certora/scripts/verifyBancorNetwork.sh reentrancyCheck511
# sh certora/scripts/verifyBancorNetwork.sh reentrancyCheck512
# sh certora/scripts/verifyBancorNetwork.sh reentrancyCheck521
# sh certora/scripts/verifyBancorNetwork.sh reentrancyCheck6
# sh certora/scripts/verifyBancorNetwork.sh almightyAdmin1
# sh certora/scripts/verifyBancorNetwork.sh almightyAdmin2
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo2
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo3
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo4
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo512
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo521
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo522
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo61
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo62
# sh certora/scripts/verifyBancorNetwork.sh whenPausedNothingToDo63
# sh certora/scripts/verifyBancorNetwork.sh flashLoanCompleteness