name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/v3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update Package Information
        run: sudo apt-get update

      - name: Install Packages
        run: sudo apt-get install libusb-1.0-0-dev libudev-dev

      - name: Install NPM Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: CI=1 yarn test

      - name: Test Migration
        run: CI=1 yarn test-migration
